{% set name = "pyspark-stubs" %}
{% set version = "3.0.0.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cb66a15e2ba2e55b377c5d48545583aa4271c0866734cd1fcb6287757673a5e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - pyspark >=3.0.0,<3.1.0
    - python >=3.6
  run:
    - pyspark >=3.0.0,<3.1.0
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/pyspark/py.typed  # [unix]
    - if not exist %SP_DIR%\\pyspark\\py.typed exit 1  # [win]

about:
  home: https://github.com/zero323/pyspark-stubs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A collection of the Apache Spark stub files
  doc_url: https://github.com/zero323/pyspark-stubs/blob/branch-2.4/README.rst
  dev_url: https://github.com/zero323/pyspark-stubs

extra:
  recipe-maintainers:
    - zero323
