travis:
  secure:
    BINSTAR_TOKEN: ZGVZIIzxvJHZriKXDI/X/JI6/2Q5iA7MBayv1JL4s/ZyD+swdCd6oMfPJ6DVPXOv35h/3jfW7n0QAZtfz+s6ZBORQSsMiv/rRITBaAVLccd+3qmVNsU3zd4Qy5Vcu6itye5U5vUl6xJ/z3swAnOe9zGNESWVk1AT/d/V+gmTRB5Yj1t3OnSNzrZaC+oZaqGYhh/ya1+HpVzgY/6oykqnijqRrqeXqdQCouyP+JFLgsWTFeAfcSr8eDmOrMTwNxYRspsyUPkwI8hLIhnHxCBp3Xj5Cio4a04muVaBYMaDCNxoyf6Y4gSD6l4/K7nHemf0NcSXVz07tuMXJ5oUwqUTlBCKgxOTo1pnkcHiyREJmUGRxgaKCBQSBB53T+3vS0qoEmzfAo8VmC0ubVQdfZbV8uEqMTh0gf5VFmtDpf5LgO57KKvLZ91Jy5pNmJaf+/Ur7SRLMCl2vgQgPDv9tJfKz/Sg3D0Y5HVVkrtnFkZ6aK7ziFXeAIgl+Et4rxM8DsbZOMhadfq3DT0YnsS7CTsW04R2aXyCRmXc+2k9ry7Plq1XkKCgj7ANKTAdHaS0yB9J+2KoSw4AVxerkASeUMIsIFIh1ZOrMVkmRmtHWeDOKezAKJitzZcBVwcJgtjmHYxESgeMMOlJs+jeBlYQgzdXCJ67hPzqr3OZO4bLpbN39fw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
